version: '3'
services:
  cql-execution:
    build:
      context: ./cql-execution-service
    ports:
      - "8080:8080"
      
  cql-storage:
    depends_on:
      - db
    build:
      context: ./cqlstorage
    ports:
      - "8081:8080"
    environment:
      JDBC_URL: "jdbc:postgresql://db:5432/db"
      JDBC_USERNAME: "postgres"
      JDBC_PASSWORD: "postgres"
      
  ecr-repository:
    build:
      context: ./ecr_repository
      
  db:
    image: postgres:11.2
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "db"
      
  fhir-filter:
    build:
      context: ./fhirfilter
    ports:
      - "8082:8080"
    environment:
      BASIC_AUTH_USER: "fhirFilter"
      BASIC_AUTH_PASSWORD: "password"
      
  job-management-system:
    depends_on:
      - db
    build:
      context: ./listManagementSystem
    ports:
      - "8083:8080"
    environment:
      JDBC_URL: "jdbc:postgresql://db:5432/db"
      JDBC_USER: "postgres"
      JDBC_PASSWORD: "postgres"
      
  results-manager:
    depends_on:
      - job-management-system
      - cql-execution
      - cql-storage
      - ecr-repository
    build:
      context: ./resultsmanager
    ports:
      - "8084:8080"
    environment:
      CQL_EXECUTION_URL: "cql-execution"
      CQL_EXECUTION_TERMINOLOGY_SERVICE: "https://cts.nlm.nih.gov/fhir/"
      #Change to fhir data provider within EHR
      CQL_EXECUTION_DATA_SERVICE: "https://apps.hdap.gatech.edu/gt-fhir/fhir/"
      CQL_EXECUTION_TERMINOLOGY_USER: "jduke99"
      CQL_EXECUTION_TERMINOLOGY_PASS: "v6R4*SsU39"
      CQL_STORAGE_URL: "cql-storage"
      FHIR_FILTER_URL: "fhir-filter"