version: '3'
services:
  cql-execution:
    build:
      context: ./cql-execution-service
      
  cql-storage:
    depends_on:
      - db
    build:
      context: ./cqlstorage
    ports:
      - "8080:8080"
    environment:
      JDBC_URL: "jdbc:postgresql://db:5432/db"
      JDBC_USERNAME: "postgres"
      JDBC_PASSWORD: "postgres"
    command: ["./wait-for", "db:5432", "--", "java -jar /usr/src/app/CQLStorage.jar"]
  db:
    build:
     context: ./db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "db"
      
  fhir-filter:
    build:
      context: ./fhirfilter
    ports:
      - "8081:8080"
    environment:
      BASIC_AUTH_USER: "fhirFilter"
      BASIC_AUTH_PASSWORD: "password"
      
  job-management-system:
    depends_on:
      - db
    build:
      context: ./jobmanagementsystem
    ports:
      - "8082:8080"
    environment:
      JDBC_URL: "jdbc:postgresql://db:5432/db"
      JDBC_USER: "postgres"
      JDBC_PASSWORD: "postgres"
      BASIC_USERNAME: "username"
      BASIC_PASSWORD: "password"
      
  nginx-cache:
    depends_on:
      - concept-translate
    build:
      context: ./nginx-cache
      
  results-manager:
    depends_on:
      - job-management-system
      - cql-execution
      - cql-storage
    build:
      context: ./resultsmanager
    environment:
      #Change to fhir data provider within the internal EHR
      CQL_EXECUTION_DATA_SERVICE: "https://apps.hdap.gatech.edu/gt-fhir/fhir/"
      #Basic authentication credentials to the data service
      CQL_EXECUTION_DATA_USER: ""
      CQL_EXECUTION_DATA_PASS: ""
      #Change if you want to use a seperate terminology service
      CQL_EXECUTION_TERMINOLOGY_SERVICE: "https://cts.nlm.nih.gov/fhir/"
      #Authorization credentials to the terminology service
      CQL_EXECUTION_TERMINOLOGY_USER: ""
      CQL_EXECUTION_TERMINOLOGY_PASS: ""
      #local code translation service
      CQL_EXECUTION_CODEMAPPER_SERVICE: "https://nginx-cache/fhir/"
      CQL_EXECUTION_CODEMAPPER_USER: "client"
      CQL_EXECUTION_CODEMAPPER_PASS: "secret"
      CQL_EXECUTION_CODEMAPPER_SYSTEMS_MAP: '{"http://www.nlm.nih.gov/research/umls/rxnorm":"http://hl7.org/fhir/ndfrt"}'
      CQL_EXECUTION_URL: "cql-execution"
      CQL_STORAGE_URL: "cql-storage"
      FHIR_FILTER_URL: "fhir-filter"
      
  translateconcept:
    depends_on:
      - db
      - cql-storage
    build:
      context: ./omoponfhir-omopv5-stu3-conceptmapping-server
    environment:
      JDBC_URL: "jdbc:postgresql://db:5432/db?currentSchema=omop_v5"
      JDBC_USERNAME: "postgres"
      JDBC_PASSWORD: "postgres"
    command: ["./wait-for", "db:5432", "--", "catalina.sh run"]